name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - altgraph
  - arrow
  - attrs
  - beautifulsoup4
  - binaryornot
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - charset-normalizer
  - click
  - colorama
  - conda
  - conda-build
  - conda-package-handling
  - cookiecutter
  - cryptography
  - dataclasses
  - delta
  - filelock
  - future
  - glob2
  - gmp
  - icu
  - idna
  - importlib-metadata
  - iniconfig
  - jinja2
  - jinja2-time
  - jsonschema
  - libarchive
  - libcxx
  - libffi
  - libiconv
  - liblief
  - libxml2
  - lz4-c
  - lzo
  - macholib
  - markupsafe
  - more-itertools
  - ncurses
  - openssl
  - packaging
  - pip
  - pkginfo
  - pluggy
  - poyo
  - psutil
  - py
  - py-lief
  - pycosat
  - pycparser
  - pycryptodome
  - pyinstaller
  - pyinstaller-hooks-contrib
  - pyopenssl
  - pyparsing
  - pyrsistent
  - pysocks
  - pytest
  - pytest-executable
  - python
  - python-dateutil
  - python-libarchive-c
  - python-slugify
  - python_abi
  - pytz
  - pyyaml
  - readline
  - requests
  - ripgrep
  - ruamel_yaml
  - setuptools
  - six
  - soupsieve
  - sqlite
  - text-unidecode
  - tk
  - toml
  - tqdm
  - typing_extensions
  - tzdata
  - unidecode
  - urllib3
  - wheel
  - whichcraft
  - xz
  - yaml
  - zipp
  - zlib
  - zstd
  - pip:
    - build
    - pep517
    - tomli
